name: Check for runtime errors
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11 #install the python needed
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: execute test script for 1 minute
        run: | #this will timeout after 1 minute, but it specifically ignores timeout errors so that the timeout will be successful
          timeout 1 python ./src/main.py test || code=$?; if [[ $code -ne 124 && $code -ne 0 ]]; then exit $code; fi
    